import FoodDataProvider from '@/lib/food-data-provider';
import { Flex } from 'antd';
import Header from '@/components/header/header';
import StyledComponentsRegistry from '@/lib/styled-registry';
import { IThemeProvider } from '@impulse-ui/toolkit';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={{ backgroundImage: `url('/images/background.jpg')` }}>
        <IThemeProvider themes={{}}>
          <FoodDataProvider>
            <StyledComponentsRegistry>
              <Flex align={'center'} vertical gap={32}>
                <Header />
                {children}
              </Flex>
            </StyledComponentsRegistry>
          </FoodDataProvider>
        </IThemeProvider>
      </body>
    </html>
  );
}
