import { Inter } from 'next/font/google';
import FoodDataProvider from '@/lib/food-data-provider';
import { Flex } from 'antd';
import Header from '@/components/header/header';
import TotalsDataGrid from '@/components/totals-data-grid/totals-data-grid';
import SearchDataGrid from '@/components/search-data-grid/search-data-grid';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={{ backgroundImage: `url('/images/background.jpg')` }} className={inter.className}>
        <FoodDataProvider>
          <Flex align={'center'} vertical gap={32}>
            <Header />
            {children}
          </Flex>
        </FoodDataProvider>
      </body>
    </html>
  );
}
