version: "3.9"

services:
  express-backend:
    container_name: express-backend
    build: ./nutritional-food-backend
    env_file:
      - ./nutritional-food-backend/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      express-backend-db:
        condition: service_healthy

  express-backend-db:
    image: 'postgres:13.1-alpine'
    container_name: express-backend-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    healthcheck:
      test: pg_isready -U compose-postgres

  nutritional-food:
    image: 'nextjs'
    build: ./nutritional-food-frontend
    container_name: nutritional-food
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - express-backend