const FOOD_NAMES = [
  'Apple',
  'Banana',
  'Chicken Breast',
  'Salmon',
  'Broccoli',
  'Quinoa',
  'Avocado',
  'Sweet Potato',
  'Oatmeal',
  'Greek Yogurt',
  'Spinach',
  'Pineapple',
  'Almonds',
  'Eggs',
  'Cottage Cheese',
  'Tomato',
  'Carrot',
  'Brown Rice',
  'Turkey',
  'Asparagus',
  'Blueberries',
  'Chickpeas',
  'Walnuts',
  'Mango',
  'Kale',
  'Peanut Butter',
  'Tofu',
  'Oranges',
  'Beef',
  'Green Beans',
  'Strawberries',
  'Cashews',
  'Lentils',
  'Cauliflower',
  'Honey',
  'Peaches',
  'Squash',
  'Raspberries',
  'Chia Seeds',
  'Pumpkin Seeds',
  'Cucumber',
  'Pears',
  'Plums',
  'Artichoke',
  'Lemon',
  'Papaya',
  'Watermelon',
  'Kiwi',
  'Blackberries',
  'Hazelnuts',
  'Shrimp',
  'Brussels Sprouts',
  'Pomegranate',
  'Cranberries',
  'Cantaloupe',
  'Figs',
  'Venison',
  'Collard Greens',
  'Romaine Lettuce',
  'Caviar',
  'Cilantro',
  'Jicama',
  'Sardines',
  'Soy Milk',
  'Bok Choy',
  'Butternut Squash',
  'Prosciutto',
  'Cranberry Sauce',
  'Arugula',
  'Radishes',
  'Clams',
  'Parsnips',
  'Endive',
  'Guava',
  'Grapes',
  'Tuna',
  'Peas',
  'Rutabaga',
  'Star Fruit',
  'Sushi',
  'Cherries',
];

const FOOD_TYPES = [
  'Fruit',
  'Vegetable',
  'Protein',
  'Grain',
  'Healthy Fat',
  'Dairy',
  'Seafood',
  'Nuts',
  'Legumes',
  'Berries',
  'Sweets',
  'Root Vegetables',
  'Leafy Greens',
  'Citrus',
  'Whole Grains',
  'Spices',
  'Herbs',
  'Condiments',
  'Tropical Fruit',
  'Melons',
  'Cruciferous Vegetables',
  'Lean Protein',
  'Shellfish',
  'Tree Nuts',
  'Dried Fruit',
  'Exotic Fruit',
  'Superfoods',
  'Fermented Foods',
  'Low-Fat Dairy',
  'Wild Game',
  'Pickles',
  'Squash',
  'Stone Fruit',
  'Cabbage',
  'Seeds',
  'Citrus Fruit',
  'Legumes',
  'Dark Leafy Greens',
  'Berries',
  'Nuts and Seeds',
  'Fresh Herbs',
  'Roots and Tubers',
  'Whole Grains',
  'Tropical Fruits',
  'Melons',
  'Mushrooms',
  'Berries',
  'Citrus Fruits',
  'Hard Cheese',
  'Crustaceans',
  'Herbs and Spices',
  'Root Vegetables',
  'Berries',
  'Exotic Meats',
  'Leafy Greens',
  'Shellfish',
  'Berries',
  'Exotic Seafood',
  'Tropical Vegetables',
  'Nuts and Legumes',
  'Exotic Herbs',
  'Cured Meats',
  'Cruciferous Greens',
  'Exotic Condiments',
  'Soft Cheese',
  'Fish Roe',
  'Tropical Nuts',
  'Berries',
  'Leafy Greens',
  'Exotic Fruits',
  'Grilled Meats',
  'Fermented Dairy',
  'Berries',
  'Exotic Vegetables',
  'Tropical Herbs',
  'Exotic Spices',
  'Marinated Seafood',
  'Berries',
  'Pickled Vegetables',
  'Exotic Nuts',
  'Leafy Greens',
  'Fermented Vegetables',
  'Exotic Berries',
  'Smoked Meats',
  'Berries',
  'Exotic Seeds',
  'Tropical Condiments',
];

export { FOOD_NAMES, FOOD_TYPES };
